# Generated by Django 4.2.1 on 2023-05-24 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coletor',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produtor.pessoa')),
                ('n_coletas', models.IntegerField(help_text='Número de Coletas')),
            ],
            bases=('produtor.pessoa',),
        ),
    ]
