# Generated by Django 4.2.1 on 2023-05-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome', max_length=200)),
                ('cpf', models.CharField(help_text='CPF', max_length=500)),
                ('email', models.CharField(help_text='Email', max_length=500)),
            ],
        ),
    ]
